@echo Installing Node.js. This will take a few minutes...
msiexec.exe /a https://nodejs.org/dist/v14.18.0/node-v14.18.0-x86.msi /quiet
@echo Setting up Lunchtime App...
npm run setup
npm run svc-install